[build-system]
requires = ["setuptools>=68", "wheel", "cython>=3.0", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "shortest_distances"
dynamic = ["version"]

[tool.setuptools_scm]
